version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "Install phase"
      - uname -a
      - apt-get update
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=$PATH:$HOME/.local/bin
#      - apt-get install pip3
#      - pip3 install pyenv


