version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "Install phase"
      - uname -a
      - apt-get update
      - pyenv install 3.8.14
      - python3 --version
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=$PATH:$HOME/.local/bin
      - apt-get install -y pip


