version: 0.2

env:
  shell: bash
  variables:
    ARTIFACTS_BUCKET:

phases:
  install:
    commands:
      - echo "Install phase"
      - uname -a
      - apt-get update
      - pyenv install 3.8.14
      - python3 --version
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH=$PATH:$HOME/.local/bin
      - apt-get install -y pip
      - pip install aws-sam-cli
  build:
    commands:
      - poetry install
      - poetry run pytest
      - sam build
  post_build:
    commands:
      - sam package --output-template-file packaged.yml --s3-bucket $ARTIFACTS_BUCKET --s3-prefix poetry-lambda-builds
      - echo "hello"

artifacts:
  files:
    - packaged.yml




