version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orestis-test-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z1ienfb81of1"
s3_prefix = "orestis-test-stack"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
